//! `use bevy_pipe_affect::prelude::*;` to import common items.

pub use either::Either;

pub use crate::effects::{
    affect_many,
    affect_or_handle,
    command_insert_resource,
    command_queue,
    command_remove_resource,
    command_spawn,
    command_spawn_and,
    components_set,
    components_set_filtered,
    components_set_filtered_with,
    components_set_filtered_with_query_data,
    components_set_with,
    components_set_with_query_data,
    entity_command_despawn,
    entity_command_insert,
    entity_command_queue,
    entity_command_remove,
    entity_components_set,
    entity_components_set_with,
    entity_components_set_with_query_data,
    message_write,
    res_set,
    res_set_with,
    AffectMany,
    AffectOrHandle,
    CommandInsertResource,
    CommandQueue,
    CommandRemoveResource,
    CommandSpawnAnd,
    ComponentsSet,
    ComponentsSetWith,
    EntityCommandDespawn,
    EntityCommandInsert,
    EntityCommandQueue,
    EntityCommandRemove,
    EntityComponentsSet,
    EntityComponentsSetWith,
    MessageWrite,
    ResSet,
    ResSetWith,
};
pub use crate::system_combinators::{affect, and_compose};
pub use crate::{Effect, EffectOut};
