//! `use bevy_pipe_affect::prelude::*;` to import common items.

pub use either::Either;

pub use crate::effects::{
    AffectMany,
    AffectOrHandle,
    CommandInsertResource,
    CommandQueue,
    CommandRemoveResource,
    CommandSpawn,
    CommandSpawnAnd,
    CommandTrigger,
    EntityCommandDespawn,
    EntityCommandInsert,
    EntityCommandInsertRecursive,
    EntityCommandQueue,
    EntityCommandRemove,
    EntityCommandRemoveRecursive,
    LocalSetAnd,
    MessageWrite,
    MessagesReadAnd,
    QueryAffect,
    QueryEntityAffect,
    QueryEntityMap,
    QueryEntityMapAnd,
    QueryMap,
    QueryMapAnd,
    ResSet,
    ResSetWith,
    affect_many,
    affect_or_handle,
    command_insert_resource,
    command_queue,
    command_remove_resource,
    command_spawn,
    command_spawn_and,
    command_trigger,
    entity_command_despawn,
    entity_command_insert,
    entity_command_insert_recursive,
    entity_command_queue,
    entity_command_remove,
    entity_command_remove_recursive,
    local_set_and,
    message_write,
    messages_read_and,
    query_affect,
    query_entity_affect,
    query_entity_map,
    query_entity_map_and,
    query_map,
    query_map_and,
    res_set,
    res_set_with,
};
#[cfg(feature = "asset_server")]
pub use crate::effects::{AssetAddAnd, AssetServerLoadAnd, asset_add_and, asset_server_load_and};
pub use crate::query_data_effects::{ComponentSet, ComponentsSet, component_set, components_set};
pub use crate::system_combinators::{
    affect,
    in_and_extend,
    in_and_then,
    in_and_then_compose,
    pure,
};
pub use crate::{Effect, EffectOut, QueryDataEffect, effect_out};
